services:
  listmonk:
    container_name: ${LISTMONK_CONTAINER_NAME:-listmonk_app}
    image: ${LISTMONK_IMAGE:-listmonk/listmonk}:${LISTMONK_VERSION:-latest}
    restart: ${RESTART_POLICY:-always}
    environment:
      LISTMONK_app__address: 0.0.0.0:${LISTMONK_PORT:-9000}
      LISTMONK_db__user: ${POSTGRES_USER:-listmonk}
      LISTMONK_db__password: ${POSTGRES_PASSWORD:-listmonk}
      LISTMONK_db__database: ${POSTGRES_DB:-listmonk}
      LISTMONK_db__host: ${LISTMONK_DB_HOST:-postgres}
      LISTMONK_db__port: ${LISTMONK_DB_PORT:-5432}
      LISTMONK_db__ssl_mode: ${LISTMONK_DB_SSL_MODE:-disable}
      LISTMONK_db__max_open: ${LISTMONK_DB_MAX_OPEN:-25}
      LISTMONK_db__max_idle: ${LISTMONK_DB_MAX_IDLE:-25}
      LISTMONK_db__max_lifetime: ${LISTMONK_DB_MAX_LIFETIME:-300s}
      TZ: ${TIMEZONE:-Asia/Bangkok}
      LISTMONK_ADMIN_USER: ${LISTMONK_ADMIN_USER:-admin}
      LISTMONK_ADMIN_PASSWORD: ${LISTMONK_ADMIN_PASSWORD:-password}
    ports:
      - "${LISTMONK_PORT:-9000}:9000"
    volumes:
      - ./uploads:/listmonk/uploads:rw
    networks:
      - default
    depends_on:
      - postgres
    hostname: ${LISTMONK_HOSTNAME:-listmonk.example.com}
    command: [sh, -c, "./listmonk --install --idempotent --yes --config '' && ./listmonk --upgrade --yes --config '' && ./listmonk --config ''"]
    
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME:-listmonk_db}
    image: ${POSTGRES_IMAGE:-postgres}:${POSTGRES_VERSION:-14-alpine}
    restart: ${RESTART_POLICY:-always}
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-listmonk}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-listmonk}
      POSTGRES_DB: ${POSTGRES_DB:-listmonk}
      TZ: ${TIMEZONE:-Asia/Bangkok}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-listmonk}"]
      interval: ${HEALTHCHECK_INTERVAL:-10s}
      timeout: ${HEALTHCHECK_TIMEOUT:-5s}
      retries: ${HEALTHCHECK_RETRIES:-6}

networks:
  default:
    name: listmonk_network
    driver: bridge

volumes:
  postgres_data:
    name: listmonk_data
    driver: local